### ISSUE TITLE
Issues while compiling and running reproduce script (logging.sh, )

### ISSUE THREAD

**Issue by shwetaiisc** [alexandervanrenen/pmembench#1]
I am getting a lot of errors while running the code.
I see the following errors while running: 
$ cmake . 
$ make 
 
 error: ‘class Task<int>’ has no member named ‘coroutine_handle’                                                                                        122 |       o.coroutine_handle = nullptr; 
 
 The same error is shown for everytime coroutine_handle is called. 

Next, while running 
$ ./logging.sh 

I see -- 
g++: error: nvml/src/nondebug/libpmem.a: No such file or directory                                        g++: error: nvml/src/nondebug/libpmemlog.a: No such file or directory  

Can you please help me rectify these issues?

**Comment by alexandervanrenen** [comment]
Hi,

The ``cmake`` file is not used for compiling the project, please use the script files in the ``reproduce`` folder. They are mostly just calls to the compiler, so you can have a look at them :)

The second error sounds like the PMDK library is not installed or compiled. Make sure you have the library. You can adjust the location in the compile script in ``reproduce/logging.sh``.

For the first issue, I am not quite sure. It sounds like you might be using an older version of the compiler. Did you use: ``-fcoroutines-ts`` (see the ``reproduce/coroutines.sh`` file). Coroutines are a rather new feature, hence you should check if your compiler supports them. If this doesn't help, maybe post the command you used to compile, the version of your compiler, and the whole out of it.

Best,
Alex

**Comment by shwetaiisc** [comment]
Hi, thanks! 
Clang++-12 worked. Apparently, the command mentioned in the logging.cpp file as a comment worked well. 
Changing 10e9 to 1000000000 worked.
